# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 582318a82ef8ad8cd3c5d701342f2fe10a6ea7c424e5256a9469d093b0d14de4953966264dd31ba56bc60e2dad41548c154e2890f9d3281bfc938852b40405a4
  google_client_id: 340166908667-2393k6rjea11mv628hgv6d7v9s9hk0ii.apps.googleusercontent.com
  google_client_secret: aJaDh4MJgPnrqqZFDnTVrKG0

test:
  secret_key_base: bce3fc8a0d7bfb959a96c1c846623a34f7ac3a777c42a74417a436943d65a35a7154589fed89103ee1d5977676ba4b86d024dd8aaf0befcb43f074856dc3c6fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: 340166908667-2393k6rjea11mv628hgv6d7v9s9hk0ii.apps.googleusercontent.com
  google_client_secret: aJaDh4MJgPnrqqZFDnTVrKG0
